# pandasの概要

In [2]:
import pandas as pd

## Series

In [3]:
ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

## DataFrame

In [4]:
df = pd.DataFrame([[10, "a", True],
                   [20, "b", False],
                   [30, "c", False],
                   [40, "d", True]])
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [5]:
import numpy as np

In [6]:
df = pd.DataFrame(np.arange(100).reshape((25, 4)))

In [7]:
df

     0   1   2   3
0    0   1   2   3
1    4   5   6   7
2    8   9  10  11
3   12  13  14  15
4   16  17  18  19
5   20  21  22  23
6   24  25  26  27
7   28  29  30  31
8   32  33  34  35
9   36  37  38  39
10  40  41  42  43
11  44  45  46  47
12  48  49  50  51
13  52  53  54  55
14  56  57  58  59
15  60  61  62  63
16  64  65  66  67
17  68  69  70  71
18  72  73  74  75
19  76  77  78  79
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [8]:
df.head()

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [9]:
df.tail()

     0   1   2   3
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [10]:
df.shape

(25, 4)

## インデックス名・カラム名

In [11]:
df = pd.DataFrame(np.arange(6).reshape((3, 2)))

In [12]:
df

   0  1
0  0  1
1  2  3
2  4  5

In [13]:
df.index = ["01", "02", "03"]
df.columns = ["A", "B"]

In [14]:
df

    A  B
01  0  1
02  2  3
03  4  5

In [15]:
named_df = pd.DataFrame(np.arange(6).reshape((3, 2)),
                        columns=["A列", "B列"],
                        index=["1行目", "2行目", "3行目"])
named_df

     A列  B列
1行目   0   1
2行目   2   3
3行目   4   5

In [17]:
pd.DataFrame({"A列": [0, 2, 4],
              "B列": [1, 3, 5]})

   A列  B列
0   0   1
1   2   3
2   4   5

## データの抽出

In [20]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(12).reshape((4, 3)),
                  columns=["A", "B", "C"],
                  index=["1行目", "2行目", "3行目", "4行目"])
df

     A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [21]:
df["A"]

1行目    0
2行目    3
3行目    6
4行目    9
Name: A, dtype: int64

In [22]:
df[["A", "B"]]

     A   B
1行目  0   1
2行目  3   4
3行目  6   7
4行目  9  10

In [23]:
df[:2]

     A  B  C
1行目  0  1  2
2行目  3  4  5

## locを使った抽出

In [25]:
# 全てのデータを抽出（コピーではなく参照）
df.loc[:, :]

     A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [26]:
df.loc[:, "A"]

1行目    0
2行目    3
3行目    6
4行目    9
Name: A, dtype: int64

In [27]:
df.loc[:, ["A", "B"]]

     A   B
1行目  0   1
2行目  3   4
3行目  6   7
4行目  9  10

In [28]:
df.loc["1行目", :]

A    0
B    1
C    2
Name: 1行目, dtype: int64

In [29]:
df.loc[["1行目", "3行目"], :]

     A  B  C
1行目  0  1  2
3行目  6  7  8

In [30]:
df.loc[["1行目"], ["A", "C"]]

     A  C
1行目  0  2

## ilocを使った抽出

In [31]:
df.iloc[1, 1]

np.int64(4)

In [32]:
df.iloc[1:, 1]

2行目     4
3行目     7
4行目    10
Name: B, dtype: int64

In [33]:
df

     A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [34]:
df.iloc[1:, :2]

     A   B
2行目  3   4
3行目  6   7
4行目  9  10

# データの読み込み・書き込み

In [52]:
import pandas as pd
import requests
from io import StringIO

In [36]:
df = pd.read_csv("data/201704health.csv",
                 encoding="utf-8")
df

            日付     歩数  摂取カロリー
0   2017-04-01   5439    2500
1   2017-04-02   2510    2300
2   2017-04-03  10238    1950
3   2017-04-04   8209    1850
4   2017-04-05   9434    1930
5   2017-04-06   7593    1800
6   2017-04-07   9320    1940
7   2017-04-08   4873    2300
8   2017-04-09  12045    1950
9   2017-04-10   7493    1850
10  2017-04-11   7289    1930
11  2017-04-12   6481    2300
12  2017-04-13  10287    1800
13  2017-04-14   8043    1940
14  2017-04-15   7435    2300
15  2017-04-16   7529    2300
16  2017-04-17   8031    1940
17  2017-04-18   8475    2300
18  2017-04-19   8132    1950
19  2017-04-20  15328    1800
20  2017-04-21  12849    1940
21  2017-04-22   4029    2300
22  2017-04-23   3890    1950
23  2017-04-24   8093    1850
24  2017-04-25   7823    1950
25  2017-04-26   7492    1850
26  2017-04-27   7203    1930
27  2017-04-28   7302    1850
28  2017-04-29   6033    2300
29  2017-04-30   4093    1950

In [39]:
# Excelファイル
df = pd.read_excel("data/201704health.xlsx")
df

            日付     歩数  摂取カロリー
0   2017-04-01   5439    2500
1   2017-04-02   2510    2300
2   2017-04-03  10238    1950
3   2017-04-04   8209    1850
4   2017-04-05   9434    1930
5   2017-04-06   7593    1800
6   2017-04-07   9320    1940
7   2017-04-08   4873    2300
8   2017-04-09  12045    1950
9   2017-04-10   7493    1850
10  2017-04-11   7289    1930
11  2017-04-12   6481    2300
12  2017-04-13  10287    1800
13  2017-04-14   8043    1940
14  2017-04-15   7435    2300
15  2017-04-16   7529    2300
16  2017-04-17   8031    1940
17  2017-04-18   8475    2300
18  2017-04-19   8132    1950
19  2017-04-20  15328    1800
20  2017-04-21  12849    1940
21  2017-04-22   4029    2300
22  2017-04-23   3890    1950
23  2017-04-24   8093    1850
24  2017-04-25   7823    1950
25  2017-04-26   7492    1850
26  2017-04-27   7203    1930
27  2017-04-28   7302    1850
28  2017-04-29   6033    2300
29  2017-04-30   4093    1950

## データ読み込み : WebサイトのHTMLから表を取得

In [44]:
url = "https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%83%E3%83%97%E3%83%AC%E3%83%99%E3%83%AB%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E4%B8%80%E8%A6%A7"
headers = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

In [56]:
response = requests.get(url, headers=headers)
html_io = StringIO(response.text)
tables = pd.read_html(html_io, flavor='html5lib')

In [57]:
len(tables)

40

In [58]:
df = tables[4]
df

,Name,Entity,Explanation,Notes,IDN,DNSSEC,SLD,IPv6
0,.ac,アセンション島,NaN,広く学術的なサイト（大学など）のために用いられる。アセンション島はイギリス領であるが、イギリ...,Yes,Yes,Yes,Yes
1,.ad,アンドラ,NaN,アンドラにおける商標または市民権が必要となる[7][8]。,NaN,Yes,Yes,NaN
2,.ae,アラブ首長国連邦,NaN,NaN,NaN,No,Yes,NaN
3,.af,アフガニスタン,NaN,NaN,NaN,Yes,Yes,NaN
4,.ag,アンティグア・バーブーダ,NaN,AGがドイツの株式会社(Aktiengesellschaft)の略称であることから、非公式に...,NaN,Yes,Yes,NaN
...,...,...,...,...,...,...,...,...
251,.ye,イエメン,NaN,NaN,NaN,No,No,NaN
252,.yt,マヨット島,NaN,欧州連合・スイス・ノルウェー・アイスランド・リヒテンシュタインの個人・企業に限る[cctld...,Yes[cctld 12],Yes,Yes,NaN
253,.za,南アフリカ,Zuid-Afrika (オランダ語),NaN,NaN,No,No,NaN
254,.zm,ザンビア,NaN,NaN,NaN,Yes,Yes[cctld 28],NaN
255,.zw,ジンバブエ,NaN,NaN,NaN,No,No,NaN